INSERT INTO OPERATOR (NAME, CTU) VALUES('Jager','GSG9');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Bandit','GSG9');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Blitz','GSG9');
INSERT INTO OPERATOR (NAME, CTU) VALUES('IQ','GSG9'); 
INSERT INTO OPERATOR (NAME, CTU) VALUES('Doc','GIGN');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Rook','GIGN');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Montagne','GIGN');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Twitch','GIGN');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Thermite','FBI');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Pulse','FBI');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Castle','FBI');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Ash','FBI');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Smoke','SAS');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Thatcher','SAS');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Mute','SAS');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Sledge','SAS');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Fuze','Spetsnaz');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Glaz','Spetsnaz');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Kapkan','Spetsnaz');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Tachanka','Spetsnaz');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Buck','JTF-2');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Frost','JTF-2');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Blackbeard','Navy Seal');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Valkyrie','Navy Seal');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Caveira','BOPE');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Capitao','BOPE');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Mira','GEO');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Jackal','GEO');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Hibana','SAT');
INSERT INTO OPERATOR (NAME, CTU) VALUES('Echo','SAT');
INSERT INTO MAP ( MAP_NAME , LOSSES , WINS , WL ) VALUES('Villa',0,0,0);
INSERT INTO MAP ( MAP_NAME , LOSSES , WINS , WL ) VALUES('Consulate',0,0,0);
INSERT INTO MAP ( MAP_NAME , LOSSES , WINS , WL ) VALUES('Bank',0,0,0);
INSERT INTO MAP ( MAP_NAME , LOSSES , WINS , WL ) VALUES('Skyscraper',0,0,0);
INSERT INTO MAP ( MAP_NAME , LOSSES , WINS , WL ) VALUES('Themepark',0,0,0);
INSERT INTO MAP ( MAP_NAME , LOSSES , WINS , WL ) VALUES('Hereford Base',0,0,0);
INSERT INTO MAP ( MAP_NAME , LOSSES , WINS , WL ) VALUES('Chalet',0,0,0);






